from __future__ import annotations

import ast
import importlib.resources
import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable

from .diagnostics import Diagnostic


@dataclass(slots=True)
class TranslationResult:
    swift: str
    diagnostics: list[Diagnostic] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not any(d.level == "error" for d in self.diagnostics)


@dataclass(slots=True)
class FunctionInfo:
    name: str
    params: list[str]
    defaults: dict[str, ast.expr]


class SwiftEmitter(ast.NodeVisitor):
    """Translate a useful, intentionally documented Python subset to Swift."""

    def __init__(self, filename: str = "<input>") -> None:
        self.filename = filename
        self.lines: list[str] = []
        self.indent = 0
        self.diagnostics: list[Diagnostic] = []
        self.scopes: list[dict[str, str]] = [dict()]
        self.function_info: dict[str, FunctionInfo] = {}
        self.class_names: set[str] = set()
        self.module_aliases: dict[str, str] = {}
        self.current_class: str | None = None
        self.current_function: str | None = None
        self.worker_functions: set[str] = set()
        self._temp_counter = 0

    def write(self, line: str = "") -> None:
        self.lines.append("    " * self.indent + line)

    def error(self, node: ast.AST, message: str) -> None:
        self.diagnostics.append(Diagnostic("error", message, getattr(node, "lineno", None), getattr(node, "col_offset", None)))

    def warn(self, node: ast.AST, message: str) -> None:
        self.diagnostics.append(Diagnostic("warning", message, getattr(node, "lineno", None), getattr(node, "col_offset", None)))

    def pre_scan(self, tree: ast.Module) -> None:
        for node in tree.body:
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                params = [a.arg for a in node.args.args]
                defaults: dict[str, ast.expr] = {}
                if node.args.defaults:
                    offset = len(params) - len(node.args.defaults)
                    for name, default in zip(params[offset:], node.args.defaults):
                        defaults[name] = default
                self.function_info[node.name] = FunctionInfo(node.name, params, defaults)
            elif isinstance(node, ast.ClassDef):
                self.class_names.add(node.name)
            elif isinstance(node, ast.Import):
                for alias in node.names:
                    self.module_aliases[alias.asname or alias.name.split(".")[0]] = alias.name
            elif isinstance(node, ast.ImportFrom) and node.module:
                for alias in node.names:
                    self.module_aliases[alias.asname or alias.name] = f"{node.module}.{alias.name}"

    def emit_module(self, tree: ast.Module) -> str:
        self.pre_scan(tree)
        self.write("// Generated by PySwift Translator. Review diagnostics before production use.")
        self.write("import Foundation")
        self.write()

        definitions: list[ast.stmt] = []
        executable: list[ast.stmt] = []
        for node in tree.body:
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                definitions.append(node)
            elif isinstance(node, (ast.Import, ast.ImportFrom)):
                self.visit(node)
            else:
                executable.append(node)

        for node in definitions:
            self.visit(node)
            self.write()

        self.emit_worker_dispatch()
        self.write()
        self.write("if !pySwiftHandledWorkerInvocation() {")
        self.indent += 1
        if executable:
            for node in executable:
                self.visit(node)
        else:
            self.write("// No top-level executable statements.")
        self.indent -= 1
        self.write("}")
        return "\n".join(self.lines).rstrip() + "\n"

    def emit_worker_dispatch(self) -> None:
        self.write("func pySwiftHandledWorkerInvocation() -> Bool {")
        self.indent += 1
        self.write("guard CommandLine.arguments.count >= 4, CommandLine.arguments[1] == \"--pyswift-worker\" else { return false }")
        self.write("let target = CommandLine.arguments[2]")
        self.write("let args = pyDecodeWorkerArgs(CommandLine.arguments[3])")
        self.write("switch target {")
        self.indent += 1
        for name, info in sorted(self.function_info.items()):
            self.write(f'case "{name}":')
            self.indent += 1
            args = []
            for i, param in enumerate(info.params):
                if param in info.defaults:
                    args.append(f"args.count > {i} ? args[{i}] : {self.expr(info.defaults[param])}")
                else:
                    args.append(f"args.count > {i} ? args[{i}] : .none")
            self.write(f"pyEmitWorkerResult({name}({', '.join(args)}))")
            self.indent -= 1
        self.write("default:")
        self.indent += 1
        self.write('fputs("Unknown PySwift worker target: \\(target)\\n", stderr)')
        self.indent -= 1
        self.indent -= 1
        self.write("}")
        self.write("return true")
        self.indent -= 1
        self.write("}")

    def push_scope(self) -> None:
        self.scopes.append({})

    def pop_scope(self) -> None:
        self.scopes.pop()

    def declare(self, name: str, kind: str = "pyvalue") -> None:
        self.scopes[-1][name] = kind

    def resolve(self, name: str) -> str | None:
        for scope in reversed(self.scopes):
            if name in scope:
                return scope[name]
        return None

    def next_temp(self) -> str:
        self._temp_counter += 1
        return f"__pyTmp{self._temp_counter}"

    # ---------- statements ----------
    def visit_Import(self, node: ast.Import) -> None:
        supported = {"math", "time", "random", "sys", "os", "json", "multiprocessing"}
        for alias in node.names:
            root = alias.name.split(".")[0]
            if root not in supported:
                self.warn(node, f"Import '{alias.name}' has no automatic Swift mapping and was omitted")

    def visit_ImportFrom(self, node: ast.ImportFrom) -> None:
        supported = {"math", "time", "random", "sys", "os", "json", "multiprocessing"}
        if (node.module or "").split(".")[0] not in supported:
            self.warn(node, f"Import from '{node.module}' has no automatic Swift mapping and was omitted")

    def visit_Expr(self, node: ast.Expr) -> None:
        if isinstance(node.value, ast.Constant) and isinstance(node.value.value, str):
            # Module/function docstring.
            text = node.value.value.replace("*/", "* /")
            self.write(f"/* {text} */")
            return
        self.write(self.expr(node.value))

    def visit_Assign(self, node: ast.Assign) -> None:
        value = self.expr(node.value)
        kind = self.infer_kind(node.value)
        if len(node.targets) > 1:
            tmp = self.next_temp()
            self.write(f"let {tmp} = {value}")
            for target in node.targets:
                self.emit_assignment(target, tmp, kind)
            return
        self.emit_assignment(node.targets[0], value, kind)

    def visit_AnnAssign(self, node: ast.AnnAssign) -> None:
        value = self.expr(node.value) if node.value else ".none"
        self.emit_assignment(node.target, value, self.infer_kind(node.value) if node.value else "pyvalue")

    def emit_assignment(self, target: ast.expr, value: str, kind: str = "pyvalue") -> None:
        if isinstance(target, ast.Name):
            existing = self.resolve(target.id)
            if existing is None:
                self.declare(target.id, kind)
                if kind == "pyvalue":
                    self.write(f"var {target.id}: PyValue = {value}")
                else:
                    self.write(f"var {target.id} = {value}")
            else:
                self.write(f"{target.id} = {value}")
            return
        if isinstance(target, ast.Attribute):
            self.write(f"{self.attribute(target)} = {value}")
            return
        if isinstance(target, ast.Subscript):
            self.write(f"{self.expr(target.value)}[{self.subscript_index(target.slice)}] = {value}")
            return
        if isinstance(target, (ast.Tuple, ast.List)):
            tmp = self.next_temp()
            self.write(f"let {tmp} = pyIterable({value})")
            for i, elt in enumerate(target.elts):
                self.emit_assignment(elt, f"{tmp}.count > {i} ? {tmp}[{i}] : .none", "pyvalue")
            return
        self.error(target, f"Unsupported assignment target: {type(target).__name__}")

    def visit_AugAssign(self, node: ast.AugAssign) -> None:
        lhs = self.assignment_target_expr(node.target)
        rhs = self.expr(node.value)
        op = self.binop(node.op, lhs, rhs)
        self.write(f"{lhs} = {op}")

    def visit_If(self, node: ast.If) -> None:
        self.write(f"if {self.expr(node.test)}.truthy {{")
        self.indent += 1
        self.emit_body(node.body)
        self.indent -= 1
        if node.orelse:
            if len(node.orelse) == 1 and isinstance(node.orelse[0], ast.If):
                self.write("} else ", )
                # Re-write the last line to produce `} else if` cleanly.
                self.lines[-1] = "    " * self.indent + f"}} else if {self.expr(node.orelse[0].test)}.truthy {{"
                self.indent += 1
                self.emit_body(node.orelse[0].body)
                self.indent -= 1
                tail = node.orelse[0].orelse
                while len(tail) == 1 and isinstance(tail[0], ast.If):
                    child = tail[0]
                    self.write(f"}} else if {self.expr(child.test)}.truthy {{")
                    self.indent += 1
                    self.emit_body(child.body)
                    self.indent -= 1
                    tail = child.orelse
                if tail:
                    self.write("} else {")
                    self.indent += 1
                    self.emit_body(tail)
                    self.indent -= 1
            else:
                self.write("} else {")
                self.indent += 1
                self.emit_body(node.orelse)
                self.indent -= 1
        self.write("}")

    def visit_While(self, node: ast.While) -> None:
        self.write(f"while {self.expr(node.test)}.truthy {{")
        self.indent += 1
        self.emit_body(node.body)
        self.indent -= 1
        self.write("}")
        if node.orelse:
            self.warn(node, "Python while...else is not preserved; else body was emitted after the loop")
            self.emit_body(node.orelse)

    def visit_For(self, node: ast.For) -> None:
        seq = self.expr(node.iter)
        item = self.next_temp()
        self.write(f"for {item} in pyIterable({seq}) {{")
        self.indent += 1
        self.bind_loop_target(node.target, item)
        self.emit_body(node.body)
        self.indent -= 1
        self.write("}")
        if node.orelse:
            self.warn(node, "Python for...else is not preserved; else body was emitted after the loop")
            self.emit_body(node.orelse)

    def bind_loop_target(self, target: ast.expr, source: str) -> None:
        if isinstance(target, ast.Name):
            if self.resolve(target.id) is None:
                self.declare(target.id)
                self.write(f"var {target.id}: PyValue = {source}")
            else:
                self.write(f"{target.id} = {source}")
        elif isinstance(target, (ast.Tuple, ast.List)):
            values = self.next_temp()
            self.write(f"let {values} = pyIterable({source})")
            for i, elt in enumerate(target.elts):
                self.bind_loop_target(elt, f"{values}.count > {i} ? {values}[{i}] : .none")
        else:
            self.error(target, "Unsupported for-loop target")

    def visit_Break(self, node: ast.Break) -> None: self.write("break")
    def visit_Continue(self, node: ast.Continue) -> None: self.write("continue")
    def visit_Pass(self, node: ast.Pass) -> None: self.write("// pass")

    def visit_Return(self, node: ast.Return) -> None:
        self.write(f"return {self.expr(node.value) if node.value else '.none'}")

    def visit_FunctionDef(self, node: ast.FunctionDef) -> None:
        if node.decorator_list:
            unsupported = [d for d in node.decorator_list if not (isinstance(d, ast.Name) and d.id in {"staticmethod", "classmethod"})]
            if unsupported:
                self.warn(node, "Function decorators are not preserved")
        old_function = self.current_function
        self.current_function = node.name
        self.push_scope()
        params = []
        positional = node.args.args
        defaults = node.args.defaults
        default_offset = len(positional) - len(defaults)
        for i, arg in enumerate(positional):
            if self.current_class and arg.arg in {"self", "cls"}:
                continue
            self.declare(arg.arg)
            if i >= default_offset:
                default = self.expr(defaults[i - default_offset])
                params.append(f"_ {arg.arg}: PyValue = {default}")
            else:
                params.append(f"_ {arg.arg}: PyValue")
        if node.args.vararg:
            self.error(node, "*args function definitions are not yet supported")
        if node.args.kwarg or node.args.kwonlyargs:
            self.error(node, "**kwargs/keyword-only function definitions are not yet supported")
        name = node.name
        if self.current_class and name == "__init__":
            self.write(f"init({', '.join(params)}) {{")
        else:
            swift_name = name
            self.write(f"func {swift_name}({', '.join(params)}) -> PyValue {{")
        self.indent += 1
        body = node.body
        if body and isinstance(body[0], ast.Expr) and isinstance(body[0].value, ast.Constant) and isinstance(body[0].value.value, str):
            self.visit(body[0]); body = body[1:]
        self.emit_body(body)
        if not (self.current_class and name == "__init__") and not self.body_always_returns(body):
            self.write("return .none")
        self.indent -= 1
        self.write("}")
        self.pop_scope()
        self.current_function = old_function

    def visit_AsyncFunctionDef(self, node: ast.AsyncFunctionDef) -> None:
        self.warn(node, "async def is currently lowered to a synchronous Swift function")
        clone = ast.FunctionDef(node.name, node.args, node.body, node.decorator_list, node.returns, node.type_comment)
        ast.copy_location(clone, node)
        self.visit_FunctionDef(clone)

    def visit_ClassDef(self, node: ast.ClassDef) -> None:
        if node.bases:
            self.warn(node, "Python inheritance is only partially supported; bases were omitted")
        attrs = self.collect_self_attributes(node)
        old_class = self.current_class
        self.current_class = node.name
        self.write(f"final class {node.name} {{")
        self.indent += 1
        for attr in sorted(attrs):
            self.write(f"var {attr}: PyValue = .none")
        if attrs:
            self.write()
        had_init = False
        for stmt in node.body:
            if isinstance(stmt, ast.FunctionDef):
                if stmt.name == "__init__": had_init = True
                self.visit(stmt)
                self.write()
            elif isinstance(stmt, ast.Pass):
                continue
            elif isinstance(stmt, ast.Expr) and isinstance(stmt.value, ast.Constant) and isinstance(stmt.value.value, str):
                self.visit(stmt)
            else:
                self.warn(stmt, "Class-level executable statements are not currently preserved")
        if not had_init:
            self.write("init() {}")
        self.indent -= 1
        self.write("}")
        self.current_class = old_class

    def visit_With(self, node: ast.With) -> None:
        if len(node.items) != 1:
            self.error(node, "Only one context manager per with-statement is supported")
            return
        item = node.items[0]
        if isinstance(item.context_expr, ast.Call) and isinstance(item.context_expr.func, ast.Name) and item.context_expr.func.id == "open":
            file_expr = self.call_expr(item.context_expr)
            self.write("do {")
            self.indent += 1
            if isinstance(item.optional_vars, ast.Name):
                self.declare(item.optional_vars.id, "file")
                self.write(f"let {item.optional_vars.id} = {file_expr}")
                self.emit_body(node.body)
                self.write(f"{item.optional_vars.id}.close()")
            else:
                self.warn(node, "with open(...) without 'as name' was lowered without a bound file")
                self.emit_body(node.body)
            self.indent -= 1
            self.write("}")
            return
        if self.is_pool_call(item.context_expr) and isinstance(item.optional_vars, ast.Name):
            self.write("do {")
            self.indent += 1
            self.declare(item.optional_vars.id, "pool")
            self.write(f"let {item.optional_vars.id} = {self.call_expr(item.context_expr)}")
            self.emit_body(node.body)
            self.write(f"{item.optional_vars.id}.close()")
            self.write(f"{item.optional_vars.id}.join()")
            self.indent -= 1
            self.write("}")
            return
        self.error(node, "Only with open(...) and multiprocessing.Pool(...) are currently supported")

    def visit_Try(self, node: ast.Try) -> None:
        self.error(node, "try/except/finally translation requires explicit error-model decisions and is not yet automatic")
        self.write("// TODO(PySwift): untranslated try/except block")

    def visit_Raise(self, node: ast.Raise) -> None:
        self.error(node, "raise is not yet translated")
        self.write("fatalError(\"Translated Python raise\")")

    def emit_body(self, body: Iterable[ast.stmt]) -> None:
        body = list(body)
        if not body:
            self.write("// empty")
            return
        for stmt in body:
            self.visit(stmt)

    def body_always_returns(self, body: list[ast.stmt]) -> bool:
        if not body: return False
        last = body[-1]
        if isinstance(last, ast.Return): return True
        if isinstance(last, ast.If) and last.orelse:
            return self.body_always_returns(last.body) and self.body_always_returns(last.orelse)
        return False

    # ---------- expressions ----------
    def expr(self, node: ast.AST | None) -> str:
        if node is None:
            return ".none"
        method = getattr(self, f"expr_{type(node).__name__}", None)
        if method is None:
            self.error(node, f"Unsupported expression: {type(node).__name__}")
            return ".none /* unsupported */"
        return method(node)

    def expr_Constant(self, node: ast.Constant) -> str:
        v = node.value
        if v is None: return ".none"
        if isinstance(v, bool): return f".bool({str(v).lower()})"
        if isinstance(v, int): return f".int({v})"
        if isinstance(v, float): return f".double({repr(v)})"
        if isinstance(v, str): return f".string({json.dumps(v)})"
        if isinstance(v, bytes):
            self.warn(node, "bytes are lowered to a UTF-8 string")
            return f".string({json.dumps(v.decode('utf-8', errors='replace'))})"
        self.error(node, f"Unsupported constant: {type(v).__name__}")
        return ".none"

    def expr_Name(self, node: ast.Name) -> str:
        if node.id == "True": return ".bool(true)"
        if node.id == "False": return ".bool(false)"
        if node.id == "None": return ".none"
        if node.id == "__name__": return '.string("__main__")'
        return node.id

    def expr_List(self, node: ast.List) -> str: return ".list([" + ", ".join(self.expr(e) for e in node.elts) + "])"
    def expr_Tuple(self, node: ast.Tuple) -> str: return ".list([" + ", ".join(self.expr(e) for e in node.elts) + "])"
    def expr_Set(self, node: ast.Set) -> str:
        self.warn(node, "set literals are lowered to lists and lose uniqueness semantics")
        return ".list([" + ", ".join(self.expr(e) for e in node.elts) + "])"

    def expr_Dict(self, node: ast.Dict) -> str:
        pairs = []
        for k, v in zip(node.keys, node.values):
            if k is None:
                self.error(node, "Dictionary **unpacking is not supported")
                continue
            key = self.expr(k)
            pairs.append(f"{key}.stringValue: {self.expr(v)}")
        return ".dict([" + ", ".join(pairs) + "])"

    def expr_BinOp(self, node: ast.BinOp) -> str: return self.binop(node.op, self.expr(node.left), self.expr(node.right))

    def binop(self, op: ast.operator, lhs: str, rhs: str) -> str:
        if isinstance(op, ast.Add): return f"({lhs} + {rhs})"
        if isinstance(op, ast.Sub): return f"({lhs} - {rhs})"
        if isinstance(op, ast.Mult): return f"({lhs} * {rhs})"
        if isinstance(op, ast.Div): return f"({lhs} / {rhs})"
        if isinstance(op, ast.Mod): return f"({lhs} % {rhs})"
        if isinstance(op, ast.Pow): return f"pyPow({lhs}, {rhs})"
        if isinstance(op, ast.FloorDiv): return f"pyFloorDiv({lhs}, {rhs})"
        if isinstance(op, ast.BitAnd): return f"pyBitAnd({lhs}, {rhs})"
        if isinstance(op, ast.BitOr): return f"pyBitOr({lhs}, {rhs})"
        if isinstance(op, ast.BitXor): return f"pyBitXor({lhs}, {rhs})"
        if isinstance(op, ast.LShift): return f"pyLShift({lhs}, {rhs})"
        if isinstance(op, ast.RShift): return f"pyRShift({lhs}, {rhs})"
        self.error(op, f"Unsupported binary operator: {type(op).__name__}")
        return ".none"

    def expr_UnaryOp(self, node: ast.UnaryOp) -> str:
        value = self.expr(node.operand)
        if isinstance(node.op, ast.USub): return f"(-{value})"
        if isinstance(node.op, ast.UAdd): return value
        if isinstance(node.op, ast.Not): return f"pyNot({value})"
        if isinstance(node.op, ast.Invert): return f"pyInvert({value})"
        self.error(node, "Unsupported unary operator")
        return ".none"

    def expr_BoolOp(self, node: ast.BoolOp) -> str:
        values = [self.expr(v) for v in node.values]
        if not values: return ".bool(false)"
        result = values[0]
        for v in values[1:]:
            if isinstance(node.op, ast.And): result = f"pyAnd({result}) {{ {v} }}"
            else: result = f"pyOr({result}) {{ {v} }}"
        return result

    def expr_Compare(self, node: ast.Compare) -> str:
        lhs = self.expr(node.left)
        pieces = []
        current = lhs
        for op, comparator in zip(node.ops, node.comparators):
            rhs = self.expr(comparator)
            if isinstance(op, ast.Eq): piece = f"pyEq({current}, {rhs})"
            elif isinstance(op, ast.NotEq): piece = f"pyNe({current}, {rhs})"
            elif isinstance(op, ast.Lt): piece = f"pyLt({current}, {rhs})"
            elif isinstance(op, ast.LtE): piece = f"pyLe({current}, {rhs})"
            elif isinstance(op, ast.Gt): piece = f"pyGt({current}, {rhs})"
            elif isinstance(op, ast.GtE): piece = f"pyGe({current}, {rhs})"
            elif isinstance(op, ast.In): piece = f"pyContains({rhs}, {current})"
            elif isinstance(op, ast.NotIn): piece = f"pyNot(pyContains({rhs}, {current}))"
            elif isinstance(op, ast.Is): piece = f"pyEq({current}, {rhs})"
            elif isinstance(op, ast.IsNot): piece = f"pyNe({current}, {rhs})"
            else:
                self.error(node, f"Unsupported comparison {type(op).__name__}"); piece = ".bool(false)"
            pieces.append(piece); current = rhs
        result = pieces[0]
        for p in pieces[1:]: result = f"pyAnd({result}) {{ {p} }}"
        return result

    def expr_IfExp(self, node: ast.IfExp) -> str: return f"({self.expr(node.test)}.truthy ? {self.expr(node.body)} : {self.expr(node.orelse)})"

    def expr_Subscript(self, node: ast.Subscript) -> str:
        if isinstance(node.slice, ast.Slice):
            s = self.expr(node.slice.lower) if node.slice.lower else ".none"
            e = self.expr(node.slice.upper) if node.slice.upper else ".none"
            st = self.expr(node.slice.step) if node.slice.step else ".none"
            return f"pySlice({self.expr(node.value)}, {s}, {e}, {st})"
        return f"{self.expr(node.value)}[{self.subscript_index(node.slice)}]"

    def subscript_index(self, node: ast.AST) -> str: return self.expr(node)

    def expr_Attribute(self, node: ast.Attribute) -> str: return self.attribute(node)

    def attribute(self, node: ast.Attribute) -> str:
        full = self.dotted_name(node)
        if full:
            mapped = self.map_module_attribute(full)
            if mapped: return mapped
        return f"{self.expr(node.value)}.{node.attr}"

    def expr_Call(self, node: ast.Call) -> str: return self.call_expr(node)

    def call_expr(self, node: ast.Call) -> str:
        # Builtins.
        if isinstance(node.func, ast.Name):
            name = node.func.id
            if name == "print":
                sep = '" "'; end = '"\\n"'
                for kw in node.keywords:
                    if kw.arg == "sep": sep = f"{self.expr(kw.value)}.stringValue"
                    elif kw.arg == "end": end = f"{self.expr(kw.value)}.stringValue"
                    else: self.warn(kw, f"print keyword '{kw.arg}' is ignored")
                return f"pyPrint([{', '.join(self.expr(a) for a in node.args)}], sep: {sep}, end: {end})"
            if name == "len": return f"pyLen({self.one_arg(node, name)})"
            if name == "int": return f"pyInt({self.one_arg(node, name, '.int(0)')})"
            if name == "float": return f"pyFloat({self.one_arg(node, name, '.double(0)')})"
            if name == "str": return f"pyStr({self.one_arg(node, name, '.string(\"\")')})"
            if name == "bool": return f"pyBool({self.one_arg(node, name, '.bool(false)')})"
            if name == "abs": return f"pyAbs({self.one_arg(node, name)})"
            if name == "sum": return f"pySum({self.one_arg(node, name)})"
            if name == "any": return f"pyAny({self.one_arg(node, name)})"
            if name == "all": return f"pyAll({self.one_arg(node, name)})"
            if name == "reversed": return f"pyReversed({self.one_arg(node, name)})"
            if name == "sorted":
                reverse = ".bool(false)"
                for kw in node.keywords:
                    if kw.arg == "reverse": reverse = self.expr(kw.value)
                    elif kw.arg == "key": self.warn(kw, "sorted(key=...) is not yet preserved")
                return f"pySorted({self.one_arg(node, name)}, reverse: {reverse})"
            if name == "min": return f"pyMin({self.one_arg(node, name)})"
            if name == "max": return f"pyMax({self.one_arg(node, name)})"
            if name == "round":
                args = [self.expr(a) for a in node.args]
                return f"pyRound({args[0] if args else '.none'}{', ' + args[1] if len(args) > 1 else ''})"
            if name == "input": return f"pyInput({self.expr(node.args[0]) if node.args else '.string(\"\")'})"
            if name == "range":
                args = [self.expr(a) for a in node.args]
                if len(args) == 1: return f"pyRange({args[0]})"
                if len(args) == 2: return f"pyRange({args[0]}, {args[1]})"
                if len(args) == 3: return f"pyRange({args[0]}, {args[1]}, {args[2]})"
                self.error(node, "range() expects 1-3 arguments"); return ".list([])"
            if name == "enumerate":
                args = [self.expr(a) for a in node.args]
                return f"pyEnumerate({args[0]}{', start: ' + args[1] if len(args)>1 else ''})" if args else ".list([])"
            if name == "zip": return f"pyZip([{', '.join(self.expr(a) for a in node.args)}])"
            if name == "list": return f".list(pyIterable({self.expr(node.args[0])}))" if node.args else ".list([])"
            if name == "dict": return ".dict([:])" if not node.args and not node.keywords else self.unsupported_call(node, "dict() construction with arguments")
            if name == "open":
                args = [self.expr(a) for a in node.args]
                mode = args[1] if len(args) > 1 else ".string(\"r\")"
                for kw in node.keywords:
                    if kw.arg == "mode": mode = self.expr(kw.value)
                return f"PyFile({args[0] if args else '.string(\"\")'}, mode: {mode})"
            if name in self.class_names:
                return f"{name}({', '.join(self.expr(a) for a in node.args)})"
            if name in self.function_info:
                return self.user_function_call(name, node)
            imported = self.module_aliases.get(name)
            if imported:
                mapped = self.map_imported_function(imported, node)
                if mapped: return mapped
            # Unknown callable: preserve as a Swift call and warn.
            if node.keywords:
                self.warn(node, f"Keywords on unknown call '{name}' may require manual Swift labels")
            return f"{name}({', '.join(self.expr(a) for a in node.args)})"

        if isinstance(node.func, ast.Attribute):
            full = self.dotted_name(node.func)
            if full:
                mapped = self.map_module_call(full, node)
                if mapped: return mapped
            receiver = node.func.value
            method = node.func.attr
            recv_expr = self.expr(receiver)
            recv_kind = self.infer_kind(receiver)
            if method == "append": return f"{recv_expr}.pyAppend({self.one_arg(node, method)})"
            if method == "extend": return f"{recv_expr}.pyExtend({self.one_arg(node, method)})"
            if method == "insert":
                args = [self.expr(a) for a in node.args]; return f"{recv_expr}.pyInsert({', '.join(args)})"
            if method == "pop": return f"{recv_expr}.pyPop({self.expr(node.args[0]) if node.args else ''})"
            if method == "remove": return f"{recv_expr}.pyRemove({self.one_arg(node, method)})"
            if method == "reverse": return f"{recv_expr}.pyReverse()"
            if method == "sort": return f"{recv_expr}.pySort()"
            if method == "keys": return f"{recv_expr}.pyKeys()"
            if method == "values": return f"{recv_expr}.pyValues()"
            if method == "items": return f"{recv_expr}.pyItems()"
            if method == "get":
                args = [self.expr(a) for a in node.args]
                return f"{recv_expr}.pyGet({args[0] if args else '.none'}{', ' + args[1] if len(args) > 1 else ''})"
            if method == "upper": return f"{recv_expr}.pyUpper()"
            if method == "lower": return f"{recv_expr}.pyLower()"
            if method == "strip": return f"{recv_expr}.pyStrip()"
            if method == "replace": return f"{recv_expr}.pyReplace({', '.join(self.expr(a) for a in node.args)})"
            if method == "startswith": return f"{recv_expr}.pyStartswith({self.one_arg(node, method)})"
            if method == "endswith": return f"{recv_expr}.pyEndswith({self.one_arg(node, method)})"
            if method == "split": return f"{recv_expr}.pySplit({self.expr(node.args[0]) if node.args else ''})"
            if method == "find": return f"{recv_expr}.pyFind({self.one_arg(node, method)})"
            if recv_kind == "process" and method in {"start", "join"}: return f"{recv_expr}.{method}()"
            if recv_kind == "pool" and method == "map":
                if len(node.args) != 2 or not isinstance(node.args[0], ast.Name):
                    self.error(node, "Pool.map currently requires a named top-level function and one iterable")
                    return ".list([])"
                target = node.args[0].id; self.worker_functions.add(target)
                return f'{recv_expr}.map(target: "{target}", items: {self.expr(node.args[1])})'
            if recv_kind == "pool" and method in {"close", "join"}: return f"{recv_expr}.{method}()"
            if recv_kind == "file" and method in {"read", "readline", "close"}: return f"{recv_expr}.{method}()"
            if recv_kind == "file" and method == "write": return f"{recv_expr}.write({self.one_arg(node, method)})"
            # Class methods and unknown methods.
            return f"{recv_expr}.{method}({', '.join(self.expr(a) for a in node.args)})"

        self.error(node, "Unsupported callable expression")
        return ".none"

    def user_function_call(self, name: str, node: ast.Call) -> str:
        info = self.function_info[name]
        positional = [self.expr(a) for a in node.args]
        values: dict[str, str] = {}
        for param, value in zip(info.params, positional): values[param] = value
        for kw in node.keywords:
            if kw.arg is None:
                self.error(node, "**kwargs call expansion is not supported")
            else:
                values[kw.arg] = self.expr(kw.value)
        rendered = []
        for param in info.params:
            if param in values: rendered.append(values[param])
            elif param in info.defaults: rendered.append(self.expr(info.defaults[param]))
            else:
                self.error(node, f"Missing required argument '{param}' in call to {name}")
                rendered.append(".none")
        return f"{name}({', '.join(rendered)})"

    def one_arg(self, node: ast.Call, name: str, default: str = ".none") -> str:
        if not node.args: return default
        if len(node.args) > 1: self.warn(node, f"{name}() extra arguments were ignored")
        return self.expr(node.args[0])

    def unsupported_call(self, node: ast.Call, description: str) -> str:
        self.error(node, f"Unsupported call: {description}")
        return ".none"

    def expr_JoinedStr(self, node: ast.JoinedStr) -> str:
        parts = []
        for value in node.values:
            if isinstance(value, ast.Constant): parts.append(str(value.value))
            elif isinstance(value, ast.FormattedValue):
                parts.append(f"\\({self.expr(value.value)}.description)")
        return f".string({json.dumps(''.join(parts)).replace('\\\\(', '\\(')})"

    def expr_ListComp(self, node: ast.ListComp) -> str:
        if len(node.generators) != 1 or not isinstance(node.generators[0].target, ast.Name):
            self.error(node, "Only single-generator list comprehensions with a simple name target are supported")
            return ".list([])"
        gen = node.generators[0]
        name = gen.target.id
        condition = " && ".join(f"{self.expr(c)}.truthy" for c in gen.ifs) or "true"
        return f".list(pyIterable({self.expr(gen.iter)}).compactMap {{ {name} in {condition} ? {self.expr(node.elt)} : nil }})"

    def expr_DictComp(self, node: ast.DictComp) -> str:
        self.error(node, "Dictionary comprehensions are not yet supported")
        return ".dict([:])"

    def expr_Lambda(self, node: ast.Lambda) -> str:
        self.error(node, "First-class Python lambdas/functions require a callable PyValue type and are not yet supported")
        return ".none"

    def expr_Await(self, node: ast.Await) -> str:
        self.warn(node, "await is currently lowered to a synchronous call")
        return self.expr(node.value)

    # ---------- mappings / helpers ----------
    def dotted_name(self, node: ast.AST) -> str | None:
        parts: list[str] = []
        cur = node
        while isinstance(cur, ast.Attribute):
            parts.append(cur.attr); cur = cur.value
        if isinstance(cur, ast.Name):
            parts.append(cur.id)
            parts.reverse()
            if parts[0] in self.module_aliases:
                root = self.module_aliases[parts[0]]
                return ".".join([root, *parts[1:]])
            return ".".join(parts)
        return None

    def map_module_attribute(self, full: str) -> str | None:
        table = {"math.pi": "pyMathPi", "sys.argv": "pySysArgv"}
        return table.get(full)

    def map_module_call(self, full: str, node: ast.Call) -> str | None:
        args = [self.expr(a) for a in node.args]
        table = {
            "math.sqrt": "pyMathSqrt", "math.sin": "pyMathSin", "math.cos": "pyMathCos", "math.tan": "pyMathTan",
            "math.floor": "pyMathFloor", "math.ceil": "pyMathCeil", "time.sleep": "pySleep", "random.random": "pyRandom",
            "random.randint": "pyRandint", "os.getenv": "pyGetenv", "os.getcwd": "pyGetcwd", "os.path.exists": "pyExists",
            "os.makedirs": "pyMkdir", "os.mkdir": "pyMkdir", "os.path.join": "pyPathJoin", "json.dumps": "pyJSONDumps", "json.loads": "pyJSONLoads",
        }
        if full in table:
            fn = table[full]
            if fn == "pyPathJoin": return f"pyPathJoin([{', '.join(args)}])"
            return f"{fn}({', '.join(args)})"
        if full == "multiprocessing.Process":
            target: str | None = None; proc_args = ".list([])"
            for kw in node.keywords:
                if kw.arg == "target" and isinstance(kw.value, ast.Name): target = kw.value.id
                elif kw.arg == "args": proc_args = self.expr(kw.value)
            if target is None:
                self.error(node, "multiprocessing.Process requires target=<top-level function>")
                target = "__missing__"
            self.worker_functions.add(target)
            return f'PyProcess(target: "{target}", args: pyIterable({proc_args}))'
        if full == "multiprocessing.Pool":
            processes = args[0] if args else ".none"
            for kw in node.keywords:
                if kw.arg in {"processes", "process"}: processes = self.expr(kw.value)
            return f"PyPool(processes: {processes})"
        return None

    def map_imported_function(self, imported: str, node: ast.Call) -> str | None:
        if "." not in imported: return None
        return self.map_module_call(imported, node)

    def is_pool_call(self, node: ast.AST) -> bool:
        return isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute) and self.dotted_name(node.func) == "multiprocessing.Pool"

    def infer_kind(self, node: ast.AST | None) -> str:
        if node is None: return "pyvalue"
        if isinstance(node, ast.Name): return self.resolve(node.id) or "pyvalue"
        if isinstance(node, ast.Call):
            if isinstance(node.func, ast.Name):
                if node.func.id in self.class_names: return f"class:{node.func.id}"
                if node.func.id == "open": return "file"
            if isinstance(node.func, ast.Attribute):
                full = self.dotted_name(node.func)
                if full == "multiprocessing.Process": return "process"
                if full == "multiprocessing.Pool": return "pool"
        return "pyvalue"

    def assignment_target_expr(self, node: ast.expr) -> str:
        if isinstance(node, ast.Name): return node.id
        if isinstance(node, ast.Attribute): return self.attribute(node)
        if isinstance(node, ast.Subscript): return f"{self.expr(node.value)}[{self.subscript_index(node.slice)}]"
        self.error(node, "Unsupported augmented-assignment target")
        return "__unsupported"

    def collect_self_attributes(self, node: ast.ClassDef) -> set[str]:
        attrs: set[str] = set()
        for child in ast.walk(node):
            if isinstance(child, ast.Attribute) and isinstance(child.value, ast.Name) and child.value.id == "self":
                if isinstance(child.ctx, (ast.Store, ast.Load)):
                    attrs.add(child.attr)
        return attrs


def runtime_source() -> str:
    return importlib.resources.files("pyswift").joinpath("templates/PyRuntime.swift").read_text(encoding="utf-8")


class Translator:
    def __init__(self, filename: str = "<input>") -> None:
        self.filename = filename

    def translate(self, source: str, *, embed_runtime: bool = False) -> TranslationResult:
        try:
            tree = ast.parse(source, filename=self.filename)
        except SyntaxError as exc:
            diag = Diagnostic("error", exc.msg, exc.lineno, (exc.offset - 1) if exc.offset else None)
            return TranslationResult("", [diag])
        emitter = SwiftEmitter(self.filename)
        body = emitter.emit_module(tree)
        swift = (runtime_source().rstrip() + "\n\n" + body) if embed_runtime else body
        return TranslationResult(swift, emitter.diagnostics)

    def translate_file(self, path: str | Path, *, embed_runtime: bool = False) -> TranslationResult:
        path = Path(path)
        return Translator(str(path)).translate(path.read_text(encoding="utf-8"), embed_runtime=embed_runtime)


def translate_source(source: str, *, filename: str = "<input>", embed_runtime: bool = False) -> TranslationResult:
    return Translator(filename).translate(source, embed_runtime=embed_runtime)
